//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace HappyTrip.Model.BusinessLayer.HappyMilesService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HappyMilesProgramSoap", Namespace="http://happymilesprogram.com/")]
    public partial class HappyMilesProgram : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHappyMilesDataForAirlineOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HappyMilesProgram() {
            this.Url = global::HappyTrip.Model.BusinessLayer.Properties.Settings.Default.HappyTrip_Model_BusinessLayer_HappyMilesService_HappyMilesProgram;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHappyMilesDataForAirlineCompletedEventHandler GetHappyMilesDataForAirlineCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://happymilesprogram.com/GetHappyMilesDataForAirline", RequestNamespace="http://happymilesprogram.com/", ResponseNamespace="http://happymilesprogram.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HappyMilesData GetHappyMilesDataForAirline(int airlineID) {
            object[] results = this.Invoke("GetHappyMilesDataForAirline", new object[] {
                        airlineID});
            return ((HappyMilesData)(results[0]));
        }
        
        /// <remarks/>
        public void GetHappyMilesDataForAirlineAsync(int airlineID) {
            this.GetHappyMilesDataForAirlineAsync(airlineID, null);
        }
        
        /// <remarks/>
        public void GetHappyMilesDataForAirlineAsync(int airlineID, object userState) {
            if ((this.GetHappyMilesDataForAirlineOperationCompleted == null)) {
                this.GetHappyMilesDataForAirlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHappyMilesDataForAirlineOperationCompleted);
            }
            this.InvokeAsync("GetHappyMilesDataForAirline", new object[] {
                        airlineID}, this.GetHappyMilesDataForAirlineOperationCompleted, userState);
        }
        
        private void OnGetHappyMilesDataForAirlineOperationCompleted(object arg) {
            if ((this.GetHappyMilesDataForAirlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHappyMilesDataForAirlineCompleted(this, new GetHappyMilesDataForAirlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://happymilesprogram.com/")]
    public partial class HappyMilesData {
        
        private int airlineIdField;
        
        private double minimumAmountField;
        
        private double exemptedAmountField;
        
        /// <remarks/>
        public int AirlineId {
            get {
                return this.airlineIdField;
            }
            set {
                this.airlineIdField = value;
            }
        }
        
        /// <remarks/>
        public double MinimumAmount {
            get {
                return this.minimumAmountField;
            }
            set {
                this.minimumAmountField = value;
            }
        }
        
        /// <remarks/>
        public double ExemptedAmount {
            get {
                return this.exemptedAmountField;
            }
            set {
                this.exemptedAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetHappyMilesDataForAirlineCompletedEventHandler(object sender, GetHappyMilesDataForAirlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHappyMilesDataForAirlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHappyMilesDataForAirlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HappyMilesData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HappyMilesData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591